config/routes.rb
Rails.application.routes.draw do

  concern :list do
    get :list, on: :collection
  end

  namespace :backend do
    resources :rides, concerns: %i[list], only: %i[index show destroy]
  end

  namespace :backend do
    resources :ride_sets, concerns: %i[list], only: %i[index show destroy] do
      member do
        get :list_rides
      end
    end

    namespace :visualizations do
      resource :ride_sets_visualizations, only: :show
      resource :rides_visualizations, only: :show
    end
    get :samsys_synchro, to: 'ride_sets#synchronize'
    get :samsys_delete_selected_ride_sets, to: 'ride_sets#delete_selected_ride_sets'
  end

end

app/controllers/backend/ride_sets_controller.rb
module Backend
  class RideSetsController < Backend::BaseController
    manage_restfully

    unroll

    list(selectable: true, order: { started_at: :desc }) do |t|
      t.column :number, url: true
      t.column :nature
      t.column :state, label_method: :decorated_state
      t.column :created_at
      t.column :started_at
      t.column :stopped_at
      t.column :duration, label_method: :decorated_duration
      t.column :sleep_count, class: 'center'
      t.column :sleep_duration, label_method: :decorated_sleep_duration
      t.column :road, class: 'center'
      t.column :main_equipment, url: { controller: 'backend/equipments', id: "RECORD.equipments.of_nature('main').first.product_id".c }
      t.column :additional_tool_one, url: { controller: 'backend/equipments', id: "RECORD.equipments.of_nature('additional')[0].product_id".c }, hidden: :additional_tool_one.nil?
      t.column :additional_tool_two, url: { controller: 'backend/equipments', id: "RECORD.equipments.of_nature('additional')[1].product_id".c }, hidden: :additional_tool_two.nil?
      t.column :provider_vendor
    end


    list(:rides, selectable: true, model: :ride, conditions: { ride_set_id: 'params[:id]'.c }, order: 'rides.started_at DESC',
line_class: 'RECORD.state'.c) do |t|
      t.column :number, url: true, class: 'ride-title'
      t.column :intervention, url: true
      t.column :nature
      t.column :started_at
      t.column :stopped_at
      t.column :duration, label_method: :decorated_duration
      t.column :sleep_count, class: 'center'
      t.column :sleep_duration, label_method: :decorated_sleep_duration
      t.column :main_equipment, url: { controller: 'backend/equipments', id: "RECORD.ride_set.equipments.of_nature('main').first.product_id".c }
      t.column :additional_tool_one, url: { controller: 'backend/equipments', id: "RECORD.ride_set.equipments.of_nature('additional')[0].product_id".c }, hidden: :additional_tool_one.nil?
      t.column :additional_tool_two, url: { controller: 'backend/equipments', id: "RECORD.ride_set.equipments.of_nature('additional')[1].product_id".c }, hidden: :additional_tool_two.nil?
      t.column :provider_vendor, label_method: :provider_vendor 
    end

    def index
      notify_ride_set_information

      if params[:ride_set_job_notify]
        notify_now(params[:ride_set_job_notify])
      end
      
      super
    end

    def synchronize
      SamsysFetchUpdateCreateJob.perform_later(stopped_on: Time.now.to_s, started_on: (Time.now - 2.days).to_s, user_id: current_user.id)
      redirect_to backend_ride_sets_path
    end

    def delete_selected_ride_sets
      SamysDeleteSelectedRideSetsJob.perform_later(ride_set_ids: params["ride_set_ids"].map(&:to_i), user_id: current_user.id)
      redirect_to backend_ride_sets_path(ride_set_job_notify: :delete_ride_set_processing.tl)
    end

    private

      def notify_ride_set_information
        if RideSet.count.zero?
          notify_warning_now(helpers.link_to(:ride_set_message.tl, backend_integrations_path))
        else
          notify_now(:ride_set_to_ride_information.tl)
        end
      end
  end
end

app/controllers/backend/rides_controller.rb
module Backend
  class RidesController < Backend::BaseController

    manage_restfully

    unroll

    def self.rides_conditions
      search_conditions(rides: [:equipment])
    end

    list(conditions: rides_conditions, order: { started_at: :desc }) do |t|
      t.action :destroy, if: :destroyable?
      t.column :number, url: true
      t.column :started_at
      t.column :stopped_at
      t.column :duration, label_method: :decorated_duration
      t.column :sleep_count, class: 'center'
      t.column :sleep_duration, label_method: :decorated_sleep_duration
      t.column :equipment, url: { controller: 'backend/equipments', id: 'RECORD.product_id'.c }
      t.column :provider_name
      t.column :state
    end
  end
end

app/controllers/backend/visualizations/ride_sets_visualizations_controller.rb
module Backend
  module Visualizations
    class RideSetsVisualizationsController < Backend::VisualizationsController
      respond_to :json

      def show
        ride_set = RideSet.find(params[:ride_set_id])
        ride_set_map = RideSetMap.new(ride_set, view_context)

        config = view_context.configure_visualization do |v|
          options = { fill_opacity: 0.2, fill_color: '#3171A9', color: '#FFFFFF', weight: 3 }
          ride_set_map.parcels_near_rides.each do |parcel|
            v.serie parcel[:name], [parcel]
            v.simple parcel[:name], parcel[:name], options
          end

          ride_set_map.rides.reverse.each do |ride|
            options = { color: ride.colors, center: ride_set.shape_centroid, ride_set: true }
            v.serie ride.name, ride.linestring
            v.polyline ride.name, ride.name, options
          end
        end

        respond_with config
      end
    end
  end
end

app/controllers/backend/visualizations/rides_visualizations_controller.rb
module Backend
  module Visualizations
    class RidesVisualizationsController < Backend::VisualizationsController
      respond_to :json

      def show
        ride = Ride.find(params[:ride_id])
        ride_map = RideMap.new(ride, view_context)

        config = view_context.configure_visualization do |v|
          options = { fill_opacity: 0.2, fill_color: '#3171A9', color: '#FFFFFF', weight: 3 }
          ride_map.parcels_near_ride.each do |parcel|
            v.serie parcel[:name], [parcel]
            v.simple parcel[:name], parcel[:name], options
          end
          v.serie :ride, ride_map.linestring
          v.polyline :ride, :ride
          v.serie :data_start_end, ride_map.start_end_crumbs
          v.points :startend, :data_start_end, colors: ['#7fbf7f', '#ff7f7f']
          if ride_map.pause_crumbs.any?
            v.serie :pause, ride_map.pause_crumbs
            v.pause_group :pause.tl, :pause
          end
        end

        respond_with config
      end
    end
  end
end

app/controllers/ekylibre_samsys/products_controller_ext.rb
module EkylibreSamsys
  module ProductsControllerExt
    extend ActiveSupport::Concern

    included do
      list(:links, model: :product_link, conditions: { product_id: 'params[:id]'.c }) do |t|
        t.column :nature
        t.column :linked_id, url: { controller: 'backend/equipments', id: 'RECORD.linked_id'.c }, label_method: :linked_name
      end
    end
  end
end

app/views/backend/ride_sets/_synchro.html.haml
- if Integration.find_by(nature: 'samsys').present?
  - job_running = Preference.get(:samsys_fetch_job_running, false, :boolean)&.value
  - main_toolbar do |t|
    = link_to :samsys_synchronisation.tl, backend_samsys_synchro_path, class: 'btn btn-default icn btn-load update-job', disabled: job_running
    - if job_running
      = content_tag(:i, nil, class: 'bqspinner')
    = link_to :samsys_delete_selected_ride_sets.tl, backend_samsys_delete_selected_ride_sets_path, class: 'disabled btn btn-default', id: 'selected-ride-sets'

app/views/backend/ride_sets/index.html.haml
%div{ id: 'notifications-tag' }
= kujaku do |k|
  - k.text
= janus do |j|
  - j.face :list do
    = main_list

app/views/backend/ride_sets/show.html.haml
= main_informations do
  = infos do
    .med-info
      %span.title= :started_at.tl
      %span.value= resource.started_at.l

    .med-info
      %span.title= :duration.tl
      %span.value= resource.decorated_duration

    - if resource.sleep_duration
      .med-info
        %span.title= :sleep_duration.tl
        %span.value= resource.decorated_sleep_duration

    .med-info
      %span.title= :road.tl
      %span.value= resource.road&.round(2)

    - if resource.area_without_overlap
      .med-info
        %span.title= :area_without_overlap.tl
        %span.value= resource.area_without_overlap.round(2).to_s + " ha"

    - if resource.area_with_overlap
      .med-info
        %span.title= :area_with_overlap.tl
        %span.value= resource.area_with_overlap.round(2).to_s + " ha"

= cobbles do |c|
  - if resource.rides.any?
    - c.cobble :map do
      = visualization(async_url: backend_visualizations_ride_sets_visualizations_path(ride_set_id: resource.id), view: {zoom: 16 }) do |v|
        - v.control :zoom
        - v.control :scale
        - v.control :fullscreen
        - v.control :layer_selector
        - v.center resource.shape_centroid

    - c.cobble(:rides) do
      = toolbar do |t|
        = t.new(nature: :record, label: :add_intervention_record.tl, params: { controller: :interventions }, class: 'disabled', id: 'new-intervention-rides')
        = t.action(:selection_modal, label: :create_from_planned_intervention.tl, params: { controller: :interventions }, class: 'disabled', id: 'intervention-request')
      = cobble_list(:rides)

app/views/backend/rides/_popup_land_parcel.html.haml
%div{ style:'display: flex; flex-direction: column; align-items: left'}
 %span{ class: 'popup-block-label'}= LandParcel.human_attribute_name(:net_surface_area)
 %span= parcel.net_surface_area
 %div{ style: 'margin-top: 1em' }= link_to LandParcel.model_name.human, backend_land_parcel_path(parcel.id), class: 'btn btn-default'

app/views/backend/rides/index.html.haml
= kujaku do |k|
  - k.text
= janus do |j|
  - j.face :list do
    = main_list

app/views/backend/rides/show.html.haml
= main_informations do
  = infos do
    .med-info
      %span.title= :started_at.tl
      %span.value= resource.started_at.l
    - if resource.sleep_duration
      .med-info
        %span.title= :sleep_duration.tl
        %span.value= resource.decorated_sleep_duration
    .med-info
      %span.title= :equipments_name.tl
      %span.value= resource.equipments_name

= cobbles do |c|
  - c.cobble :map do
    = visualization(async_url: backend_visualizations_rides_visualizations_path(ride_id: resource.id), view: {zoom: 16}) do |v|
      - v.control :zoom
      - v.control :scale
      - v.control :fullscreen
      - v.control :layer_selector
      - v.center resource.crumbs.first.geolocation.coordinates.reverse if resource.crumbs.first.present?

app/views/backend/visualizations/ride_sets_visualizations/_popup.haml
%div{ style:'display: flex; flex-direction: column; align-items: center'}
 %span
  = link_to :ride_number.tl + ' : ' + ride.number, backend_ride_path(ride.id)

app/views/backend/visualizations/rides_visualizations/_popup.haml
%div{ style:'display: flex; flex-direction: column; align-items: left'}
 %span
  = :ride_paused_at.tl + ' : ' + crumb.metadata["start_date"].to_time.strftime("%H:%M:%S")
 %span
  = :ride_duration.tl + ' : ' +  Time.at(crumb.metadata["duration"]).utc.strftime("%H:%M:%S")